# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gZ9BWAZgMdoeEXYNVl1puHpPlLmof68X
"""

import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/train.csv')

# Setting the style for seaborn
sns.set(style="whitegrid")

# 1. Bar Plot: Average Price by Owner Type
avg_price_by_owner = df.groupby('Owner_Type')['Price'].mean().reset_index()
plt.figure(figsize=(8, 5))
sns.barplot(data=avg_price_by_owner, x='Owner_Type', y='Price', palette='viridis')
plt.title("Average Car Price by Owner Type")
plt.xlabel("Owner Type")
plt.ylabel("Average Price (in lakhs)")
plt.show()

# 2. Scatter Plot: Price vs. Kilometers Driven, colored by Fuel Type
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='Kilometers_Driven', y='Price', hue='Location', palette='rainbow', s=100)
plt.title("Price vs Kilometers Driven (Colored by Location)")
plt.xlabel("Kilometers Driven")
plt.ylabel("Price (in lakhs)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Selecting relevant numerical columns for the pair plot
numerical_columns = ['Kilometers_Driven', 'Mileage', 'Engine', 'Power', 'Seats', 'Price']

# Creating the pair plot
sns.pairplot(df[numerical_columns], diag_kind='kde', plot_kws={'alpha': 0.6, 's': 40})
plt.suptitle("Pair Plot of Numerical Features", y=1.02)  # Title above the plot
plt.show()